### ISSUE TITLE
No Longer Maintained

### ISSUE THREAD

**Issue by Mactastic1-5** [RaduMC/UnityStudio#29]
It's been a year and there has been no updates or mergers from other repositories that have been maintaining their own fork of this repository. Use: https://github.com/Perfare/UnityStudio instead! Don't post your issues here!

**Comment by RaduMC** [comment]
Please stop spamming my project.

I don't know what your problem is, or why your replies seem to be so negative, but you're not helping anyone.

It's no secret that I have stopped maintaining this project a long time ago, but that doesn't mean I should just throw it away.
I posted the code here to help others understand the format and inner-workings of Unity files. No other project or extractor came even close to the level of detail you will find here.

If you want to be helpful, take the information you find here or in my Max script, which has been distributed many years ago, and build a better tool.
Don't forget to mention where you found the information. Writing tools with "nice error code" is one thing, reverse engineering an entire suite of unknown formats is a whole different animal.

**Comment by Mactastic1-5** [comment]
@RaduMC I'm not spamming your project, but it looks like everyone else is. If you maintained this project, then there probably wouldn't be so much spam on the Issues page. People keep posting their issues here and they won't get support, so it only makes sense to redirect them to a place where they can get support. There is no information here, but the code, which is available at another fork that no one knows about. This version of Unity Studio comes up on Google, not the maintained version, so don't tell me what to do and how to act. People don't have to credit you on GitHub when it's forked or cloned, there is a reference to this repository when doing so. You're not the only one that has reverse engineered Unity's proprietary formats, there are several other projects that may or may not be based on your code.  I never said you should delete this repository, you should disable the "Issues" and "Wiki" pages and redirect people to the maintained repository.

**Comment by RaduMC** [comment]
First of all I asked you politely, and I believe I even said "please";
So there's no need to throw a tantrum about me telling you what to do.

"People don't have to credit you on GitHub when it's forked or cloned, there is a reference to this repository when doing so."
And so is a reference from here to that fork as well as all others.
Closing the Issues and Wiki pages will not help people find other forks any better.

You have wasted enough of the little time I have. Go mind your own please.

**Comment by RaduMC** [comment]
Oh and one more thing. This "version" comes up first on Google for a reason. Think hard.
You are welcome to help maintain it and submit pull requests if your intent is to HELP. If not... well I already told you what to do.
